# Generated by Django 5.2.14 on 2026-06-01 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_movie_options_movie_backdrop_url_movie_genres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='vote_average',
        ),
    ]
