# Generated by Django 5.2.14 on 2026-06-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_movie_vote_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='distributor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(fields=('franchise', 'title', 'release_year'), name='unique_movie_in_franchise'),
        ),
    ]
